#!/usr/bin/env python3
"""
Protected Mode Single-Step Test Runner for z486

Runs JSON format test files generated by gen386pm (86Box reference emulator).
Tests the z486 CPU implementation in protected mode against 86Box's behavior.
"""

import json
import subprocess as sp
import tempfile
import argparse
from pathlib import Path
from multiprocessing import Pool, cpu_count
import os
import re
import sys

# Paths
ROOT = Path(__file__).resolve().parents[1]
TESTS = ROOT / 'tests'
TB = Path(os.environ.get('Z486_TESTBENCH', TESTS / 'obj_dir' / 'Vtb_z486'))
TEST_DIR = TESTS / 'singlestep_protected' / 'v1'

VERBOSE = False


def build_if_needed():
    """Build the testbench via make (handles dependency checking)."""
    if os.environ.get('Z486_TESTBENCH'):
        if not TB.exists():
            raise SystemExit(f"Requested testbench does not exist: {TB}")
        return
    sp.check_call(['make', '-s', 'obj_dir/Vtb_z486'], cwd=str(TESTS))


def write_memhex(ram_entries):
    """
    Write sparse hex file for testbench $readmemh.
    ram_entries: list of [addr, value] pairs (byte-level)
    Returns: path to temporary hex file
    """
    f = tempfile.NamedTemporaryFile(mode='w', suffix='.hex', delete=False,
                                    dir=str(TESTS))
    # Group by 4-byte aligned address for readmemh
    for addr, val in sorted(ram_entries, key=lambda x: x[0]):
        f.write(f"@{addr:X} {val:02X}\n")
    f.close()
    return f.name


def parse_seg_result(line):
    """Parse RESULT SEG line into dict.
    Format: RESULT SEG: cs base=0x00000000 limit=0xfffff flags=0xa1e0
    Or:     RESULT SEG: tr sel=0x0028 base=0x00004000 limit=0x00067 flags=0xb120
    Returns: (seg_name, {base, limit, flags, [sel]})
    """
    parts = line.split(':', 1)[1].strip()
    seg_name = parts.split()[0]
    base_m = re.search(r'base=0x([0-9a-fA-F]+)', parts)
    limit_m = re.search(r'limit=0x([0-9a-fA-F]+)', parts)
    flags_m = re.search(r'flags=0x([0-9a-fA-F]+)', parts)
    sel_m = re.search(r'sel=0x([0-9a-fA-F]+)', parts)
    result = {
        'base': int(base_m.group(1), 16) if base_m else 0,
        'limit': int(limit_m.group(1), 16) if limit_m else 0,
        'flags': int(flags_m.group(1), 16) if flags_m else 0,
    }
    if sel_m:
        result['sel'] = int(sel_m.group(1), 16)
    return seg_name, result


def run_test(test, verbose=False, notrace=True):
    """
    Run a single test case through the z486 testbench.

    Args:
        test: Test case dictionary (from JSON)
        verbose: Enable verbose trace output
        notrace: Disable VCD tracing (faster)

    Returns:
        tuple: (passed, errors, output_lines)
    """
    name = test.get('name', 'unknown')
    init = test['initial']
    fin = test['final']

    init_regs = init.get('regs', {})
    init_segs = init.get('segs', {})
    init_dtables = init.get('dtables', {})
    cr0_val = init.get('cr0', 1)  # Default: protected mode

    # Prepare RAM entries (instruction bytes + any initial RAM)
    ram_entries = init.get('ram', [])

    # Place instruction bytes at CS:EIP physical address
    # (prefetch bypasses paging, so we need bytes at the linear address)
    instr_bytes = test.get('bytes', [])
    if instr_bytes:
        cs_base = init_segs.get('cs', {}).get('base', 0)
        eip = init_regs.get('eip', 0)
        code_addr = cs_base + eip
        for i, b in enumerate(instr_bytes):
            ram_entries.append([code_addr + i, b])

    memhex = write_memhex(ram_entries)

    # Build command
    cmd = [str(TB), f"+mem={memhex}", "+cycles=50000"]

    if notrace:
        cmd.append("+notrace")

    if verbose:
        cmd.extend([
            "+trace_decode",
            "+trace_ucode",
            "+trace_sptr",
            "+trace_ldsg",
            "+trace_prot",
            "+trace_descw",
        ])

    # CR0
    cmd.append(f"+cr0={cr0_val}")

    # General registers
    for reg in ['eax', 'ecx', 'edx', 'ebx', 'esp', 'ebp', 'esi', 'edi']:
        val = init_regs.get(reg, 0)
        cmd.append(f"+{reg}={val}")

    # EIP and EFLAGS
    cmd.append(f"+ip={init_regs.get('eip', 0)}")
    cmd.append(f"+eflags={init_regs.get('eflags', 2)}")

    # Segment selectors
    for seg in ['cs', 'ds', 'es', 'ss', 'fs', 'gs']:
        seg_info = init_segs.get(seg, {})
        sel = seg_info.get('sel', 0)
        cmd.append(f"+{seg}={sel}")

    # Segment caches (only when PE=1)
    if cr0_val & 1:
        for seg in ['cs', 'ds', 'es', 'ss', 'fs', 'gs']:
            seg_info = init_segs.get(seg, {})
            cmd.append(f"+{seg}_base={seg_info.get('base', 0)}")
            cmd.append(f"+{seg}_limit={seg_info.get('limit', 0xFFFFF)}")
            cmd.append(f"+{seg}_flags={seg_info.get('flags', 0x21E0)}")

        # GDT/IDT
        gdt = init_dtables.get('gdt', {})
        idt = init_dtables.get('idt', {})
        cmd.append(f"+gdt_base={gdt.get('base', 0)}")
        cmd.append(f"+gdt_limit={gdt.get('limit', 0x3FF)}")
        cmd.append(f"+idt_base={idt.get('base', 0)}")
        cmd.append(f"+idt_limit={idt.get('limit', 0x3FF)}")

    # CR3
    cr3_val = init.get('cr3', 0)
    if cr3_val:
        cmd.append(f"+cr3={cr3_val}")

    # Task register
    tr_info = init.get('tr', {})
    if tr_info.get('sel', 0):
        cmd.append(f"+tr_sel={tr_info['sel']}")
        cmd.append(f"+tr_base={tr_info.get('base', 0)}")
        cmd.append(f"+tr_limit={tr_info.get('limit', 0)}")
        cmd.append(f"+tr_flags={tr_info.get('flags', 0)}")

    # Release segment caches if test requires it
    if init.get('release_segs', False):
        cmd.append("+release_segs")

    # Request RAM outputs we need to check
    final_ram = fin.get('ram', [])
    for i, (addr, _) in enumerate(final_ram):
        cmd.append(f"+ram{i}={addr}")

    if verbose:
        print(f"\nTest: {name}")
        print(f"Instruction bytes: {' '.join(f'{b:02x}' for b in test.get('bytes', []))}")
        print(f"Command: {' '.join(cmd)}")

    # Run testbench
    try:
        p = sp.run(cmd, cwd=str(TESTS), stdout=sp.PIPE, stderr=sp.STDOUT, text=True)
        out = p.stdout

        # Parse results
        result_fault_vector = None
        result_regs = {}
        result_segs = {}
        mem_results = {}

        for line in out.splitlines():
            if line.startswith('RESULT REG:'):
                vals = line.split(':', 1)[1].strip().split()
                for val in vals:
                    if '=' in val:
                        k, v = val.split('=')
                        k = k.lower()
                        if k == 'ip':
                            k = 'eip'
                        if v.startswith('0x'):
                            result_regs[k] = int(v, 16)
                        else:
                            result_regs[k] = int(v)
            elif line.startswith('RESULT SEG:'):
                seg_name, seg_data = parse_seg_result(line)
                result_segs[seg_name] = seg_data
            elif line.startswith('RESULT MEM:'):
                parts = line.split(':', 1)[1].strip().split('=')
                if len(parts) == 2:
                    addr = int(parts[0][1:])  # Remove '@' prefix
                    mem_results[addr] = int(parts[1])
            elif line.startswith('RESULT FAULT:'):
                m = re.search(r'vector=(\d+)', line)
                if m:
                    result_fault_vector = int(m.group(1))

        # Check for TIMEOUT
        if 'TIMEOUT' in out:
            return False, [f"TIMEOUT: test {name}"], out.splitlines()

        # Compare results
        ok = True
        errors = []

        # Fault expectation: if present, just note it for diagnostics.
        # Actual correctness is verified via registers, segments, and RAM
        # (which encode the full post-fault state including stack pushes).
        expected_fault = fin.get('fault')

        # Check registers
        final_regs = fin.get('regs', {})
        for reg, expected in final_regs.items():
            reg = reg.lower()
            got = result_regs.get(reg)

            if got is None:
                errors.append(f"Register {reg} not found in results")
                ok = False
                continue

            # Mask EFLAGS bits that are undefined for certain instructions
            if reg == 'eflags':
                # Mask reserved bits and RF (bit 16)
                mask = 0xFFFEFFFF  # mask out RF
                expected = expected & mask
                got = got & mask

            if got != expected:
                errors.append(f"{reg}: expected 0x{expected:08x}, got 0x{got:08x}")
                ok = False

        # Check segments
        final_segs = fin.get('segs', {})
        for seg, expected_seg in final_segs.items():
            got_seg = result_segs.get(seg)
            if got_seg is None:
                errors.append(f"Segment {seg} not found in results")
                ok = False
                continue

            # Check selector (from result_regs for normal segs, from RESULT SEG for tr/ldt)
            if 'sel' in expected_seg:
                if 'sel' in got_seg:
                    got_sel = got_seg['sel']
                else:
                    got_sel = result_regs.get(seg, 0)
                if got_sel != expected_seg['sel']:
                    errors.append(f"{seg}.sel: expected 0x{expected_seg['sel']:04x}, got 0x{got_sel:04x}")
                    ok = False

            # Check base
            if 'base' in expected_seg and got_seg['base'] != expected_seg['base']:
                errors.append(f"{seg}.base: expected 0x{expected_seg['base']:08x}, got 0x{got_seg['base']:08x}")
                ok = False

            # Check limit (86Box reports byte limit; our testbench reports 20-bit field)
            if 'limit' in expected_seg:
                exp_limit = expected_seg['limit']
                got_limit = got_seg['limit']
                # Convert 86Box byte limit to 20-bit field if needed
                exp_flags = expected_seg.get('flags', 0)
                if exp_limit > 0xFFFFF:
                    if exp_flags & 0x40:  # G bit set
                        exp_limit = (exp_limit >> 12) & 0xFFFFF
                    else:
                        exp_limit = 0xFFFFF  # Null selector: byte limit can't fit in 20-bit
                if got_limit != exp_limit:
                    errors.append(f"{seg}.limit: expected 0x{exp_limit:05x}, got 0x{got_limit:05x}")
                    ok = False

            # Check flags
            if 'flags' in expected_seg and got_seg['flags'] != expected_seg['flags']:
                errors.append(f"{seg}.flags: expected 0x{expected_seg['flags']:04x}, got 0x{got_seg['flags']:04x}")
                ok = False

        # Check RAM
        for addr, expected_val in final_ram:
            got_val = mem_results.get(addr)
            if got_val is None:
                errors.append(f"RAM @{addr:08x} not found in results")
                ok = False
            elif got_val != expected_val:
                errors.append(f"RAM @{addr:08x}: expected 0x{expected_val:02x}, got 0x{got_val:02x}")
                ok = False

        return ok, errors, out.splitlines()
    finally:
        os.unlink(memhex)


def run_test_wrapper(args):
    """Wrapper for multiprocessing Pool."""
    test, = args
    return run_test(test, verbose=False, notrace=True)


def extract_category(test):
    """Extract category from test dict. Uses 'category' JSON field if present,
    otherwise falls back to heuristic parsing of the test name."""
    if isinstance(test, dict) and 'category' in test:
        return test['category']
    # Fallback for old test files without category field
    name = test.get('name', 'unknown') if isinstance(test, dict) else str(test)
    struct = name.split(' ', 1)[0] if ' ' in name else name
    parts = struct.split('_')
    if parts and parts[-1].isdigit():
        parts = parts[:-1]
    return parts[-1] if parts else 'unknown'


def generate_html_report(opcode_results, total_pass, total_fail, total_skip, report_path):
    """Generate HTML report from collected results.

    opcode_results: list of dicts, each with:
        'opcode': str, 'mnemonic': str,
        'categories': dict mapping category_name -> {
            'total': int, 'passed': int, 'failed': int, 'skipped': int,
            'has_fault': bool, 'errors': list of (test_name, error_list)
        }
    """
    from datetime import datetime

    total_ran = total_pass + total_fail
    pass_pct = (total_pass / total_ran * 100) if total_ran else 0

    html = []
    html.append('''<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>z486 PM Singlestep Test Report</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif;
         background: #f6f8fa; color: #24292f; padding: 24px; line-height: 1.5; }
  h1 { margin-bottom: 8px; }
  .summary { background: #fff; border: 1px solid #d0d7de; border-radius: 6px;
             padding: 16px; margin-bottom: 20px; }
  .summary-bar { height: 8px; border-radius: 4px; background: #cf222e; margin: 10px 0; overflow: hidden; }
  .summary-bar .pass { background: #1a7f37; height: 100%; }
  .summary-stats { display: flex; gap: 24px; flex-wrap: wrap; }
  .stat { font-size: 14px; }
  .stat b { font-size: 20px; }
  .opcode-card { background: #fff; border: 1px solid #d0d7de; border-radius: 6px;
                 margin-bottom: 12px; overflow: hidden; }
  .opcode-header { display: flex; align-items: center; padding: 10px 16px;
                   cursor: pointer; user-select: none; gap: 12px; }
  .opcode-header:hover { background: #f6f8fa; }
  .opcode-tag { font-family: monospace; font-weight: 600; font-size: 15px;
                background: #ddf4ff; color: #0969da; padding: 2px 8px;
                border-radius: 4px; min-width: 60px; text-align: center; }
  .cat-section { margin-bottom: 24px; }
  .cat-header { display: flex; align-items: center; gap: 12px; padding: 8px 0 6px;
                border-bottom: 2px solid #d0d7de; margin-bottom: 8px; }
  .cat-header-name { font-family: monospace; font-weight: 700; font-size: 16px;
                     color: #8250df; text-transform: uppercase; }
  .cat-header-bar { flex: 0 0 200px; }
  .opcode-mnem { font-size: 14px; color: #57606a; flex: 1; }
  .opcode-result { font-size: 13px; font-weight: 600; padding: 2px 10px;
                   border-radius: 12px; white-space: nowrap; }
  .result-pass { background: #dafbe1; color: #1a7f37; }
  .result-fail { background: #ffebe9; color: #cf222e; }
  .result-partial { background: #fff8c5; color: #9a6700; }
  .opcode-body { border-top: 1px solid #d0d7de; padding: 0; display: none; }
  .opcode-card.open .opcode-body { display: block; }
  .opcode-card.open .arrow { transform: rotate(90deg); }
  .arrow { transition: transform 0.15s; font-size: 12px; color: #57606a; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; padding: 6px 16px; background: #f6f8fa; color: #57606a;
       font-weight: 600; border-bottom: 1px solid #d0d7de; }
  td { padding: 5px 16px; border-bottom: 1px solid #eee; }
  tr:last-child td { border-bottom: none; }
  .cat-name { font-family: monospace; }
  .bar-cell { width: 200px; }
  .mini-bar { height: 6px; border-radius: 3px; background: #eee; overflow: hidden; }
  .mini-bar .fill-pass { background: #1a7f37; height: 100%; }
  .mini-bar .fill-fail { background: #cf222e; height: 100%; float: left; }
  .mini-bar .fill-skip { background: #d4a72c; height: 100%; float: left; }
  .cnt { text-align: right; font-family: monospace; white-space: nowrap; }
  .badge { display: inline-block; padding: 1px 6px; border-radius: 8px; font-size: 11px; font-weight: 600; }
  .badge-pass { background: #dafbe1; color: #1a7f37; }
  .badge-fail { background: #ffebe9; color: #cf222e; }
  .badge-skip { background: #fff8c5; color: #9a6700; }
  .errors { margin: 0; padding: 4px 16px 4px 32px; font-size: 12px; color: #cf222e;
            font-family: monospace; background: #fff5f5; }
  .errors li { margin: 1px 0; }
  .timestamp { font-size: 12px; color: #8b949e; margin-top: 12px; }
  .filter-bar { margin-bottom: 16px; display: flex; gap: 8px; }
  .filter-btn { padding: 4px 12px; border: 1px solid #d0d7de; border-radius: 6px;
                background: #fff; cursor: pointer; font-size: 13px; }
  .filter-btn.active { background: #0969da; color: #fff; border-color: #0969da; }
</style>
</head><body>
<h1>z486 Protected Mode Singlestep Test Report</h1>
''')

    # Summary
    html.append(f'<div class="summary">')
    html.append(f'<div class="summary-stats">')
    html.append(f'<div class="stat"><b>{total_pass}</b> passed</div>')
    html.append(f'<div class="stat"><b>{total_fail}</b> failed</div>')
    if total_skip:
        html.append(f'<div class="stat"><b>{total_skip}</b> skipped</div>')
    html.append(f'<div class="stat"><b>{total_ran}</b> total ({pass_pct:.1f}%)</div>')
    html.append(f'</div>')
    html.append(f'<div class="summary-bar"><div class="pass" style="width:{pass_pct:.1f}%"></div></div>')
    html.append(f'</div>')

    # Filter buttons
    html.append('<div class="filter-bar">')
    html.append('<button class="filter-btn active" onclick="filterCards(\'all\', this)">All</button>')
    html.append('<button class="filter-btn" onclick="filterCards(\'fail\', this)">Failing</button>')
    html.append('<button class="filter-btn" onclick="filterCards(\'pass\', this)">Passing</button>')
    html.append('</div>')

    # Group opcode_results by file_category
    from collections import OrderedDict
    cat_groups = OrderedDict()
    for opc in opcode_results:
        fc = opc.get('file_category', 'other')
        cat_groups.setdefault(fc, []).append(opc)

    for group_cat, group_opcodes in cat_groups.items():
        # Compute group totals
        grp_pass = sum(sum(c['passed'] for c in o['categories'].values()) for o in group_opcodes)
        grp_fail = sum(sum(c['failed'] for c in o['categories'].values()) for o in group_opcodes)
        grp_total = grp_pass + grp_fail
        grp_pct = (grp_pass / grp_total * 100) if grp_total else 0

        if grp_fail == 0:
            grp_cls = 'result-pass'
            grp_txt = 'PASS'
        elif grp_pass == 0:
            grp_cls = 'result-fail'
            grp_txt = 'FAIL'
        else:
            grp_cls = 'result-partial'
            grp_txt = f'{grp_pass}/{grp_total}'

        html.append(f'<div class="cat-section">')
        html.append(f'  <div class="cat-header">')
        html.append(f'    <span class="cat-header-name">{group_cat}</span>')
        html.append(f'    <span class="cat-header-bar"><div class="mini-bar" style="width:200px">'
                    f'<div class="fill-pass" style="width:{grp_pct}%;float:left"></div>'
                    f'<div class="fill-fail" style="width:{100-grp_pct:.1f}%;float:left"></div>'
                    f'</div></span>')
        html.append(f'    <span class="opcode-result {grp_cls}">{grp_txt}</span>')
        html.append(f'  </div>')

        # Opcode cards within this group
        for opc in group_opcodes:
            cats = opc['categories']
            opc_total = sum(c['passed'] + c['failed'] for c in cats.values())
            opc_pass = sum(c['passed'] for c in cats.values())
            opc_fail = sum(c['failed'] for c in cats.values())
            opc_skip = sum(c['skipped'] for c in cats.values())

            if opc_fail == 0:
                result_cls = 'result-pass'
                result_txt = 'PASS'
                card_data = 'pass'
            elif opc_pass == 0:
                result_cls = 'result-fail'
                result_txt = 'FAIL'
                card_data = 'fail'
            else:
                result_cls = 'result-partial'
                result_txt = f'{opc_pass}/{opc_total}'
                card_data = 'fail'

            skip_note = f' +{opc_skip} skip' if opc_skip else ''
            html.append(f'  <div class="opcode-card" data-status="{card_data}">')
            html.append(f'    <div class="opcode-header" onclick="this.parentElement.classList.toggle(\'open\')">')
            html.append(f'      <span class="arrow">&#9654;</span>')
            html.append(f'      <span class="opcode-tag">{opc["opcode"]}</span>')
            html.append(f'      <span class="opcode-mnem">{opc["mnemonic"]}</span>')
            html.append(f'      <span class="opcode-result {result_cls}">{result_txt}{skip_note}</span>')
            html.append(f'    </div>')
            html.append(f'    <div class="opcode-body"><table>')
            html.append(f'      <tr><th>Test type</th><th>Result</th><th class="bar-cell">Progress</th><th></th></tr>')

            for cat_name, cat in sorted(cats.items(), key=lambda x: x[0]):
                cat_ran = cat['passed'] + cat['failed']
                cat_pct = (cat['passed'] / cat_ran * 100) if cat_ran else 0
                fail_pct = (cat['failed'] / cat_ran * 100) if cat_ran else 0

                if cat['failed'] == 0 and cat['passed'] > 0:
                    badge = f'<span class="badge badge-pass">{cat["passed"]}/{cat_ran}</span>'
                elif cat['passed'] == 0 and cat['failed'] > 0:
                    badge = f'<span class="badge badge-fail">0/{cat_ran}</span>'
                else:
                    badge = f'<span class="badge badge-fail">{cat["passed"]}/{cat_ran}</span>'

                if cat['skipped'] > 0:
                    badge += f' <span class="badge badge-skip">{cat["skipped"]} skip</span>'

                html.append(f'      <tr>')
                html.append(f'        <td class="cat-name">{cat_name}</td>')
                html.append(f'        <td>{badge}</td>')
                html.append(f'        <td class="bar-cell"><div class="mini-bar">'
                            f'<div class="fill-pass" style="width:{cat_pct}%;float:left"></div>'
                            f'<div class="fill-fail" style="width:{fail_pct}%;float:left"></div>'
                            f'</div></td>')
                html.append(f'        <td class="cnt">{cat["passed"]}P {cat["failed"]}F</td>')
                html.append(f'      </tr>')

                # Show first few errors for failed tests
                if cat['errors']:
                    html.append(f'      <tr><td colspan="4"><ul class="errors">')
                    for tname, errs in cat['errors'][:3]:
                        err_str = '; '.join(errs[:2])
                        more = ' ...' if len(errs) > 2 else ''
                        html.append(f'        <li><b>{tname}</b>: {err_str}{more}</li>')
                    if len(cat['errors']) > 3:
                        html.append(f'        <li>... and {len(cat["errors"]) - 3} more</li>')
                    html.append(f'      </ul></td></tr>')

            html.append(f'    </table></div>')
            html.append(f'  </div>')

        html.append(f'</div>')

    html.append(f'<div class="timestamp">Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</div>')

    # JavaScript for filtering
    html.append('''
<script>
function filterCards(mode, btn) {
  document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
  document.querySelectorAll('.cat-section').forEach(section => {
    let cards = section.querySelectorAll('.opcode-card');
    let anyVisible = false;
    cards.forEach(card => {
      if (mode === 'all') { card.style.display = ''; anyVisible = true; }
      else {
        let show = card.dataset.status === mode;
        card.style.display = show ? '' : 'none';
        if (show) anyVisible = true;
      }
    });
    section.style.display = anyVisible ? '' : 'none';
  });
}
</script>
</body></html>''')

    report_path.write_text('\n'.join(html))
    return report_path


def main():
    global VERBOSE

    parser = argparse.ArgumentParser(description='Protected Mode Single-Step Test Runner')
    parser.add_argument('-f', '--file', help='JSON test file name (without path)')
    parser.add_argument('-i', '--index', type=int, default=None, help='Run specific test index')
    parser.add_argument('-n', '--count', type=int, default=10, help='Max tests per file (default: 10)')
    parser.add_argument('-v', '--verbose', action='store_true', help='Verbose output')
    parser.add_argument('-j', '--jobs', type=int, default=None, help='Parallel jobs')
    parser.add_argument('--dir', type=str, default=None, help='Test directory override')
    parser.add_argument('--skip-faults', action='store_true', help='Skip tests that expect faults')
    parser.add_argument('-nt', '--notrace', action='store_true', help='Do not generate trace.vcd waveform')
    parser.add_argument('--html', type=str, default=None, nargs='?', const='pm_report.html',
                        help='Generate HTML report (default: pm_report.html)')
    args = parser.parse_args()

    VERBOSE = args.verbose
    test_dir = Path(args.dir) if args.dir else TEST_DIR

    build_if_needed()

    if not TB.exists():
        print(f"Testbench not found: {TB}")
        print(f"Run 'make build' in {TESTS} first")
        sys.exit(1)

    if not test_dir.exists():
        print(f"Test directory not found: {test_dir}")
        sys.exit(1)

    # Find test files
    if args.file:
        json_files = [test_dir / args.file]
        if not json_files[0].exists():
            # Try with .json extension
            json_files = [test_dir / f"{args.file}.json"]
        if not json_files[0].exists():
            print(f"Test file not found: {args.file}")
            sys.exit(1)
    else:
        json_files = sorted(test_dir.glob('*.json'))

    if not json_files:
        print(f"No test files found in {test_dir}")
        sys.exit(1)

    total_pass = 0
    total_fail = 0
    total_skip = 0
    passing_files = []
    failing_files = []
    opcode_results = []  # For HTML report

    for json_path in json_files:
        with open(json_path) as f:
            tests = json.load(f)

        if args.index is not None:
            if args.index < len(tests):
                tests = [tests[args.index]]
            else:
                print(f"Index {args.index} out of range (file has {len(tests)} tests)")
                continue

        tests = tests[:args.count]

        file_pass = 0
        file_fail = 0
        file_skip = 0

        # Extract instruction mnemonic and category from first test
        first_test = tests[0] if tests else {}
        first_name = first_test.get('name', '')
        instr_mnem = first_name.split(' ', 1)[1] if ' ' in first_name else ''
        file_cat = extract_category(first_test)
        label_str = f"{json_path.stem:8s} [{file_cat}] {instr_mnem}"
        print(f"{label_str}:")

        # Per-category tracking
        categories = {}

        for ti, test in enumerate(tests):
            name = test.get('name', 'unknown')
            has_fault = 'fault' in test.get('final', {})
            cat = extract_category(test)

            if cat not in categories:
                categories[cat] = {'total': 0, 'passed': 0, 'failed': 0,
                                   'skipped': 0, 'has_fault': False, 'errors': []}

            if args.skip_faults and has_fault:
                file_skip += 1
                categories[cat]['skipped'] += 1
                categories[cat]['has_fault'] = True
                continue

            categories[cat]['total'] += 1

            ok, errors, output = run_test(test, verbose=VERBOSE, notrace=args.notrace)

            if ok:
                file_pass += 1
                categories[cat]['passed'] += 1
                if VERBOSE:
                    print(f"  PASS [{ti}]: {name}")
                    print("  --- Output ---")
                    for line in output:
                        print(f"    {line}")
            else:
                file_fail += 1
                categories[cat]['failed'] += 1
                categories[cat]['errors'].append((name, errors))
                print(f"  FAIL [{ti}]: {name}")
                for err in errors:
                    print(f"    {err}")
                if VERBOSE:
                    print("  --- Output ---")
                    for line in output:
                        print(f"    {line}")

        total_pass += file_pass
        total_fail += file_fail
        total_skip += file_skip

        ran = file_pass + file_fail
        status = "PASS" if file_fail == 0 else "FAIL"
        skip_msg = f" ({file_skip} skipped)" if file_skip else ""
        print(f"  {file_pass}/{ran} passed [{status}]{skip_msg}")

        label = json_path.stem
        if file_fail == 0:
            passing_files.append((label, instr_mnem, file_cat))
        else:
            failing_files.append((label, instr_mnem, file_cat))

        opcode_results.append({
            'opcode': json_path.stem,
            'mnemonic': instr_mnem,
            'file_category': file_cat,
            'categories': categories,
        })

    skip_msg = f" ({total_skip} skipped)" if total_skip else ""
    print(f"\nTotal: {total_pass} PASS, {total_fail} FAIL out of {total_pass + total_fail}{skip_msg}")

    # Group results by category
    cat_groups = {}
    for label, mnem, cat in passing_files + failing_files:
        cat_groups.setdefault(cat, {'pass': [], 'fail': []})
    for label, mnem, cat in passing_files:
        cat_groups[cat]['pass'].append(f"{label}({mnem})")
    for label, mnem, cat in failing_files:
        cat_groups[cat]['fail'].append(f"{label}({mnem})")

    for cat in sorted(cat_groups):
        g = cat_groups[cat]
        items = []
        if g['pass']:
            items.append(f"PASS: {', '.join(g['pass'])}")
        if g['fail']:
            items.append(f"FAIL: {', '.join(g['fail'])}")
        print(f"  [{cat}] {'; '.join(items)}")

    # Generate HTML report
    if args.html is not None:
        report_path = Path(args.html)
        generate_html_report(opcode_results, total_pass, total_fail, total_skip, report_path)
        print(f"\nHTML report: {report_path.resolve()}")

    print(f"\n{total_pass} PASS, {total_fail} FAIL")

    if total_fail > 0:
        sys.exit(1)


if __name__ == '__main__':
    main()
