#!/usr/bin/env python3
"""Generate the synchronous CORDIC angle ROM used by x87_trans."""

from decimal import Decimal, ROUND_HALF_EVEN, getcontext
from pathlib import Path


getcontext().prec = 180

ITERATIONS = 80
FRACTION_BITS = 80
WIDTH = 83
DEPTH = 128
PI = Decimal(
    "3.141592653589793238462643383279502884197169399375105820974944592307"
    "81640628620899862803482534211706798214808651328230664709384460955058"
    "223172535940812848111745028410270193852110555964462294895493038196"
)


def atan_power_of_two(index: int) -> Decimal:
    if index == 0:
        return PI / 4

    x = Decimal(1) / (Decimal(2) ** index)
    x_squared = x * x
    term = x
    result = term
    denominator = 3
    subtract = True
    while term:
        term *= x_squared
        contribution = term / denominator
        if contribution.copy_abs() < Decimal(2) ** -170:
            break
        result = result - contribution if subtract else result + contribution
        denominator += 2
        subtract = not subtract
    return result


def scaled(value: Decimal) -> int:
    return int((value * (1 << FRACTION_BITS)).to_integral_value(
        rounding=ROUND_HALF_EVEN
    ))


def scaled_to(value: Decimal, fraction_bits: int) -> int:
    return int((value * (1 << fraction_bits)).to_integral_value(
        rounding=ROUND_HALF_EVEN
    ))


def main() -> None:
    root = Path(__file__).resolve().parent
    values = [scaled(atan_power_of_two(index))
              for index in range(ITERATIONS)]

    mif = [
        f"WIDTH={WIDTH};",
        f"DEPTH={DEPTH};",
        "ADDRESS_RADIX=HEX;",
        "DATA_RADIX=HEX;",
        "CONTENT BEGIN",
    ]
    digits = (WIDTH + 3) // 4
    for address, value in enumerate(values):
        mif.append(f"    {address:02X} : {value:0{digits}X};")
    mif.append(f"    [{ITERATIONS:02X}..{DEPTH - 1:02X}] : 0;")
    mif.append("END;")
    (root / "x87_cordic_atan.mif").write_text(
        "\n".join(mif) + "\n", encoding="ascii"
    )

    cases = [
        "// Generated by build_x87_cordic_table.py. Do not edit by hand.",
        "function automatic logic signed [82:0] x87_cordic_atan_constant(",
        "    input logic [6:0] index",
        ");",
        "    case (index)",
    ]
    for address, value in enumerate(values):
        cases.append(f"        7'd{address}: return 83'h{value:0{digits}x};")
    cases.extend([
        "        default: return 83'h0;",
        "    endcase",
        "endfunction",
    ])
    (root / "x87_cordic_atan.svh").write_text(
        "\n".join(cases) + "\n", encoding="ascii"
    )

    # Keep the differential model independent from production width changes.
    reference_values = [
        scaled_to(atan_power_of_two(index), 80)
        for index in range(ITERATIONS)
    ]
    reference_cases = [
        "// Generated by build_x87_cordic_table.py. Do not edit by hand.",
        "function automatic logic signed [82:0] x87_cordic_atan_q80_constant(",
        "    input logic [6:0] index",
        ");",
        "    case (index)",
    ]
    for address, value in enumerate(reference_values):
        reference_cases.append(
            f"        7'd{address}: return 83'h{value:021x};"
        )
    reference_cases.extend([
        "        default: return 83'h0;",
        "    endcase",
        "endfunction",
    ])
    reference_path = root.parent / "tests" / "x87_reference" / \
        "x87_cordic_atan_q80.svh"
    reference_path.write_text(
        "\n".join(reference_cases) + "\n", encoding="ascii"
    )

    print(f"wrote {ITERATIONS} Q{FRACTION_BITS} production and Q80 reference angles")


if __name__ == "__main__":
    main()
